name: Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.14.2
      - run: npm ci

      - name: ESLint
        run: npm run lint

      - name: Build
        run: npm run build --if-present

      - name: Unit test and Code coverage
        run: npm run coverage

      - name: E2E Test
        run: npm run e2e
